### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ptdtan** [lilab-bcb/pegasus#77] opened 2020-07-30 06:15 UTC
Hi,

I ran cumulus workflow 1.0.0, which uses pegasuspy 1.0.0rc1,  then got the Illegal instruction error (Logs below).
I tried pegasus 0.17.2 and it worked well.

root@1b3c2ea85480:/data/execution# **pegasus cluster ../inputs/179402141/GSE122969_data_mat_CD8_counts_WT_iso_treated.tsv Tan_attempt1 -p 32 --select-singlets --output-filtration-results --plot-filtration-results --output-h5ad --louvain --umap**
2020-07-30 06:00:23,158 - pegasusio.readwrite - INFO - tsv file '../inputs/179402141/GSE122969_data_mat_CD8_counts_WT_iso_treated.tsv' is loaded.
2020-07-30 06:00:23,158 - pegasusio.readwrite - INFO - Function 'read_input' finished in 11.66s.
2020-07-30 06:00:23,158 - pegasus - INFO - Inputs are loaded.
2020-07-30 06:00:23,330 - pegasus.tools.preprocessing - INFO - Filtration results for unknown-rna are written.
2020-07-30 06:00:24,682 - pegasus.tools.preprocessing - INFO - Filtration plots are generated.
2020-07-30 06:00:24,817 - pegasusio.qc_utils - INFO - After filtration, 5433 out of 5470 cell barcodes are kept in UnimodalData object unknown-rna.
2020-07-30 06:00:25,044 - pegasus.tools.preprocessing - INFO - After filtration, 15241/27933 genes are kept. Among 15241 genes, 13363 genes are robust.
2020-07-30 06:00:25,044 - pegasus.tools.preprocessing - INFO - Function '_run_filter_data' finished in 1.88s.

2020-07-30 06:00:25,045 - pegasus - INFO - Begin to analyze UnimodalData unknown-rna.
2020-07-30 06:00:25,423 - pegasus.tools.preprocessing - INFO - Function 'log_norm' finished in 0.38s.
2020-07-30 06:00:25,611 - pegasus.tools.hvf_selection - INFO - 2000 highly variable features have been selected.
2020-07-30 06:00:25,612 - pegasus.tools.hvf_selection - INFO - Function 'highly_variable_features' finished in 0.19s.
2020-07-30 06:00:26,578 - pegasus.tools.preprocessing - INFO - Function 'pca' finished in 0.97s.
Illegal instruction (core dumped)

**Comment by yihming** [comment] 2020-07-31 03:04
Hi,

May I know which OS you were using? Also, could you please share the output of `pip list` command?

**Comment by YichaoOU** [comment] 2021-03-15 06:09
Hello,

I'm having the same problem, here is the pip list:

(pegasus) [yli11@nodecn202 chenggrp_213991_10x]$ cat out.list 
Package            Version
------------------ -------------------
adjustText         0.7.3
anndata            0.7.5
annoy              1.17.0
asciitree          0.3.3
brotlipy           0.7.0
cached-property    1.5.2
certifi            2020.12.5
cffi               1.14.5
chardet            4.0.0
cryptography       3.4.6
cycler             0.10.0
demuxEM            0.1.5.post1
docopt             0.6.2
fasteners          0.14.1
fbpca              1.0
fitsne             1.1.0
forceatlas2-python 1.1
geosketch          1.2
gprofiler-official 1.0.0
h5py               3.1.0
harmony-pytorch    0.1.6
hnswlib            0.5.1
idna               2.10
importlib-metadata 3.7.3
intervaltree       2.1.0
joblib             1.0.1
kiwisolver         1.3.1
leidenalg          0.8.3
lightgbm           3.1.1
llvmlite           0.36.0
loompy             2.0.16
louvain            0.7.0
matplotlib         3.3.4
mkl-service        2.3.0
monotonic          1.5
msgpack            1.0.2
natsort            7.1.1
numba              0.53.0
numcodecs          0.7.3
numpy              1.19.5
olefile            0.46
packaging          20.9
pandas             1.2.3
patsy              0.5.1
pegasusio          0.2.10
pegasuspy          1.2.0
Pillow             8.1.2
pip                21.0.1
pyarrow            0.17.1
pybind11           2.6.2
pybind11-global    2.6.2
pycairo            1.20.0
pycparser          2.20
pynndescent        0.5.2
pyOpenSSL          20.0.1
pyparsing          2.4.7
PySocks            1.7.1
python-dateutil    2.8.1
python-igraph      0.8.3
pytz               2021.1
requests           2.25.1
scanorama          1.7
scikit-learn       0.24.1
scikit-misc        0.1.3
scipy              1.6.0
seaborn            0.11.1
setuptools         49.6.0.post20210108
six                1.15.0
sortedcontainers   2.3.0
statsmodels        0.12.2
texttable          1.6.3
threadpoolctl      2.1.0
torch              1.4.0
tornado            6.1
umap-learn         0.5.1
urllib3            1.26.3
wheel              0.36.2
xlrd               2.0.1
XlsxWriter         1.3.7
zarr               2.6.1
zipp               3.4.1

**Comment by yihming** [comment] 2021-03-15 21:25
Hi @YichaoOU . This is usually caused by one of the dependency package `hnswlib`, as it needs recompilation regarding the specific CPU instruction set on your machine in some circumstances. You may want to try the following command in your Python environment:
```
pip install hnswlib --force-reinstall --no-cache-dir
```
Please let me know if the issue still remains.

**Comment by YichaoOU** [comment] 2021-03-16 02:33
Nice! It worked. Thanks!

**Comment by yihming** [comment] 2021-03-16 21:30
No problem. And I'll work on resolving this issue with `hnswlib` (https://github.com/nmslib/hnswlib/issues/292) when I have time. Will let you know once it's ready.

**Closed as completed** 2021-03-16 21:30 UTC

**Comment by yihming** [comment] 2022-03-20 01:18
Hello @ptdtan @YichaoOU ,

hnswlib version 0.6.1+ has added the runtime AVX check, which should be able to resolve your problem. Please check it out.
